# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-github-webhook
  description: This component provisions a GitHub webhook for a single GitHub repository
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component





